
export const LIST_CATEGORY = 'LIST_CATEGORY'
export const LIST_CATEGORY_PENDING = 'LIST_CATEGORY_PENDING'
export const LIST_CATEGORY_SUCCESS = 'LIST_CATEGORY_SUCCESS'
export const LIST_CATEGORY_FAILURE = 'LIST_CATEGORY_FAILURE'
