
export const NEW_ANIMAL = 'NEW_ANIMAL'
export const NEW_ANIMAL_SUCCESS = 'NEW_ANIMAL_SUCCESS'

export const CREATE_ANIMAL = 'CREATE_ANIMAL'
export const CREATE_ANIMAL_PENDING = 'CREATE_ANIMAL_PENDING'
export const CREATE_ANIMAL_SUCCESS = 'CREATE_ANIMAL_SUCCESS'
export const CREATE_ANIMAL_FAILURE = 'CREATE_ANIMAL_FAILURE'

export const LIST_ANIMAL = 'LIST_ANIMAL'
export const LIST_ANIMAL_PENDING = 'LIST_ANIMAL_PENDING'
export const LIST_ANIMAL_SUCCESS = 'LIST_ANIMAL_SUCCESS'
export const LIST_ANIMAL_FAILURE = 'LIST_ANIMAL_FAILURE'

export const CHANGE_ANIMAL_STATUS = 'CHANGE_ANIMAL_STATUS'
export const CHANGE_ANIMAL_STATUS_PENDING = 'CHANGE_ANIMAL_STATUS_PENDING'
export const CHANGE_ANIMAL_STATUS_SUCCESS = 'CHANGE_ANIMAL_STATUS_SUCCESS'
export const CHANGE_ANIMAL_STATUS_FAILURE = 'CHANGE_ANIMAL_STATUS_FAILURE'
